### ISSUE TITLE
Remove os.execute

### ISSUE THREAD

**Issue by Wuzzy2** [ac-minetest/boneworld#1]
This mod uses `os.execute` but this is dangerous as this makes the mod platform-dependent.

Hint: You can use `minetest.mkdir` to create directories, you don't need `os.execute`.

**Comment by ac-minetest** [comment]
Fixed by using  `minetest.mkdir`

The reason i used os.execute was cause there isn't lua way to do it ( you need https://keplerproject.github.io/luafilesystem library).
